### ISSUE TITLE
Application doesn't provide a fallback for when a user clicks "Block" on geolocation

### ISSUE THREAD

**Issue by axeberg** [chas-academy/08-weather-app-Diasks#1]
@Diasks when the user clicks "Block" on the geolocation prompt in the browser it would be nice with a fallback.

The fallback can be a text message that says: "Whoops, couldn't find you. Either your browser doesn't support geolocation or you clicked block. We require the use of geolocation to show you data, so try and click the icon in the right side of your address bar and clearing your settings for future visits, reload the page and click "Allow"".

**Comment by Diasks** [comment]
@axelolsson Fixed!

**Comment by axeberg** [comment]
Good job!
